# Generated by Django 5.2.2 on 2025-12-15 11:37

import django.db.models.deletion
import user_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='-', max_length=50)),
                ('last_name', models.CharField(default='-', max_length=50)),
                ('phone_number', models.CharField(default='-', max_length=15)),
                ('dob', models.DateField(default='-')),
                ('identity_type', models.CharField(default='-', max_length=30)),
                ('identity_number', models.CharField(default='-', max_length=30)),
                ('gender', models.CharField(default='-', max_length=6)),
                ('profile_pic', models.ImageField(null=True, upload_to=user_management.models.generate_unique_name)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Personal_Details',
            },
        ),
    ]
