# Generated by Django 5.2.2 on 2025-12-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='dob',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
