# Generated by Django 5.1.4 on 2025-01-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adultappointments',
            name='preferred_doctor',
        ),
        migrations.RemoveField(
            model_name='childappointments',
            name='preferred_doctor',
        ),
    ]
