# Generated by Django 5.1.4 on 2025-01-17 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adultpatient',
            table='adult_patients',
        ),
        migrations.AlterModelTable(
            name='childpatient',
            table='child_patients',
        ),
    ]
