# Generated by Django 5.1.4 on 2025-01-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_adultappointments_preferred_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adultappointments',
            name='visit_reason',
        ),
        migrations.RemoveField(
            model_name='childappointments',
            name='visit_reason',
        ),
    ]
