# Generated by Django 5.1.4 on 2025-01-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_adultappointments_visit_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultappointments',
            name='appointment_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='childappointments',
            name='appointment_time',
            field=models.CharField(max_length=50),
        ),
    ]
